### ISSUE TITLE
Could not use in NestJS environment

### ISSUE THREAD

**Issue by ejabu** [kensnyder/sql-love#3]
Hi @kensnyder , amazing library ! I really love the chaining `where` clause.

However, I could not installed it in NestJs environment.

```



Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mac/dev/nestjs/node_modules/.pnpm/sql-love@1.0.2/node_modules/sql-love/dist/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at Function.Module._load (/Users/mac/dev/nestjs/node_modules/.pnpm/@nx+js@17.3.2_b7776ae7ecd8125166a744c0f5f828e8/node_modules/@nx/js/src/executors/node/node-with-require-overrides.js:18:31)
    at Array.__webpack_modules__ (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:186:18)
    at __webpack_require__ (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:209:41)
    at Array.<anonymous> (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:87:20)
    at __webpack_require__ (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:209:41)
    at Array.Object.defineProperty.value (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:55:23)
    at __webpack_require__ (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:209:41)
    at Array.<anonymous> (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:25:26)
    at __webpack_require__ (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:209:41)
    at /Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:228:22
    at /Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:239:3
    at Object.<anonymous> (/Users/mac/dev/nestjs/dist/apps/asset-vuln-service/main.js:244:12)
    at Function.Module._load (/Users/mac/dev/nestjs/node_modules/.pnpm/@nx+js@17.3.2_b7776ae7ecd8125166a744c0f5f828e8/node_modules/@nx/js/src/executors/node/node-with-require-overrides.js:10:31)
    at async Promise.all (index 0)

Waiting for the debugger to disconnect...

```

I tried to add `type: module` in package.json, but still got an error.

Please let me know what should I do, Thanks !

**Comment by kensnyder** [comment]
@ejabu This should be fixed in version 1.0.4. The package now includes 2 bundles: one for Common JS and one for ESM. Let me know if it works for you.
